const authUrl = 'http://localhost:3001/auth';
const REGISTER_UPDATE_PARAMS = "REGISTER_UPDATE_PARAMS";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_FAILURE = "REGISTER_FAILURE";
const SIGNIN_UPDATE_PARAMS = "SIGNIN_UPDATE_PARAMS";
const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
const SIGNIN_FAILURE = "SIGNIN_FAILURE";



export {
  authUrl,
  REGISTER_UPDATE_PARAMS,
  REGISTER_SUCCESS,
  REGISTER_FAILURE,
  SIGNIN_UPDATE_PARAMS,
  SIGNIN_SUCCESS,
  SIGNIN_FAILURE
};
