// url

const authUrl = 'http://localhost:3001/auth';
const API_URL = 'http://localhost:3001';

// register
const REGISTER_UPDATE_PARAMS = "REGISTER_UPDATE_PARAMS";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_FAILURE = "REGISTER_FAILURE";

//signin
const SIGNIN_UPDATE_PARAMS = "SIGNIN_UPDATE_PARAMS";
const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
const SIGNIN_FAILURE = "SIGNIN_FAILURE";

// photoBook
const FETCH_PHOTO_BOOKS_REQUEST = "FETCH_PHOTO_BOOKS_REQUEST";
const FETCH_PHOTO_BOOKS_SUCCESS = "FETCH_PHOTO_BOOKS_SUCCESS";
const FETCH_PHOTO_BOOKS_FAILURE = "FETCH_PHOTO_BOOKS_FAILURE";
const PHOTO_BOOK_UPDATE_PARAMS = "PHOTO_BOOK_UPDATE_PARAMS";
const PHOTO_BOOK_CREATE_SUCCESS = "PHOTO_BOOK_CREATE_SUCCESS";
const PHOTO_BOOK_CREATE_FAILURE = "PHOTO_BOOK_CREATE_FAILURE";
const PHOTO_BOOK_DELETE = "PHOTO_BOOK_DELETE";
const PHOTO_BOOK_DELETE_SUCCESS = "PHOTO_BOOK_DELETE_SUCCESS";
const PHOTO_BOOK_DELETE_FAILURE = "PHOTO_BOOK_DELETE_FAILURE";


export {
  authUrl,
  API_URL,
  REGISTER_UPDATE_PARAMS,
  REGISTER_SUCCESS,
  REGISTER_FAILURE,
  SIGNIN_UPDATE_PARAMS,
  SIGNIN_SUCCESS,
  SIGNIN_FAILURE,
  FETCH_PHOTO_BOOKS_REQUEST,
  FETCH_PHOTO_BOOKS_SUCCESS,
  FETCH_PHOTO_BOOKS_FAILURE,
  PHOTO_BOOK_UPDATE_PARAMS,
  PHOTO_BOOK_CREATE_SUCCESS,
  PHOTO_BOOK_CREATE_FAILURE,
  PHOTO_BOOK_DELETE,
  PHOTO_BOOK_DELETE_SUCCESS,
  PHOTO_BOOK_DELETE_FAILURE
};
